### ISSUE TITLE
Unused code TmdbID

### ISSUE THREAD

**Issue by nduhamel** [odwrtw/polochon#43]
See:

```
grep -nwr ./ -e "TmdbID"
```

Used only in the module and not in the library, any reason for keeping it inside Movie object?

**Comment by gregdel** [comment]
No good reason I guess. Do you want to remove it from the Movie struct ?

**Comment by nduhamel** [comment]
Used by kodi, no ?

**Comment by PouuleT** [comment]
We'll keep it =)
