### ISSUE TITLE
Remove NewFileWithConfig us NewFile instead

### ISSUE THREAD

**Issue by nduhamel** [odwrtw/polochon#53]

**Comment by gregdel** [comment]
Why ?

**Comment by PouuleT** [comment]
NewFileWithConfig is only used in the organizer when the file needs it to check if it's a video, if it's ignored, etc ...
We could delete NewFileWithConfig and edit all the methods on the File to take the needed config
Example:
```
f.Video.IsVideo(videoExtensions)
```

Or just let it like that =)
