### ISSUE TITLE
Bad date on Shows

### ISSUE THREAD

**Issue by PouuleT** [odwrtw/polochon#60]
1969 is the default date for all tv shows

**Comment by nduhamel** [comment]
so outdated ?

**Comment by gregdel** [comment]
Here's the NFO generated for the show "Heroes Reborn" (tvshow.nfo)
```
<tvshow>
  <title>Heroes Reborn</title>
  <showtitle>Heroes Reborn</showtitle>
  <rating>7</rating>
  <plot>A year ago, a terrorist attack in Odessa, Texas left the city decimated. Blamed for the tragic event, those with extraordinary abilities are in hiding or on the run from those with nefarious motives.</plot>
  <episodeguide>
    <url>http://www.thetvdb.com/api/1D62F2F90030C444/series/279201/all/en.zip</url>
  </episodeguide>
  <tvdbid>279201</tvdbid>
  <imdbid>tt3556944</imdbid>
  <year>2015</year>
</tvshow>
```

The year is properly set in the NFO but KODI still displays "1969" on the interface

**Comment by gregdel** [comment]
Furthermore, on each episode of this show, the "aired" field is set but the interface displays "01-01-2016" for each episode...

WTF ?

**Comment by gregdel** [comment]
I found the solution for the show year, the "year" field is not used to display the show year on the KODI interface, only the "<premiered>" field is being used !
We should patch the NFO generation to add this field :)

**Comment by gregdel** [comment]
Same shit for the episodes dates, we should set the "premiered" field, this is the only one being used to display the date on the interface
