### ISSUE TITLE
inotify does not handle the directories properly

### ISSUE THREAD

**Issue by gregdel** [odwrtw/polochon#69]
touching a file inside a directory does not trigger the "organizer"

**Comment by PouuleT** [comment]
"Inotify monitoring of directories is not recursive: to monitor subdirectories under a directory, additional watches must be created. This can take a significant amount time for large directory trees."

Taken from : http://man7.org/linux/man-pages/man7/inotify.7.html

**Comment by xunien** [comment]
https://lwn.net/Articles/605128/
