### ISSUE TITLE
Muliple episode file not handled

### ISSUE THREAD

**Issue by gregdel** [odwrtw/polochon#81]
When two episodes are in the same video file, polochon handles it as one episode (the first one)
e.g. S01E0102 => S01E01

**Comment by PouuleT** [comment]
And what should be the expected behaviour?

**Comment by gregdel** [comment]
We could set up bookmarks in the NFO so that KODI knows where to start each episode, see this [link](http://kodi.wiki/view/Naming_video_files/TV_shows#Multi-episode)

If haven't figured out yet how to make KODI display two entries for a single file. According to the documentation: 

    For multi-part episodes, simply add multiple <episodedetails> XML blocks in succession. 

I've tried to had multiple "episodedetails" entries to a single file, but it doesn't seems to be working so far. If I force KODI to read the NFO again, the first time the first episode alone is displayed, the second time only the second episode is displayed...

**Comment by gregdel** [comment]
Here is the output of guessit for a multiple episode file :
```json
{
    "container": "mkv",
    "episodeList": 
    [
        ​1,
        ​2
    ],
    "episodeNumber": ​1,
    "format": "HDTV",
    "mimetype": "video/x-matroska",
    "releaseGroup": "DIMENSION[EtHD]",
    "screenSize": "720p",
    "season": ​1,
    "series": "Heroes Reborn",
    "type": "episode",
    "videoCodec": "h264"
}
```

**Comment by gregdel** [comment]
I've forced KODI to refresh the library and it now woking.
We should add both episode informations in the same nfo setting the bookmark for the second one (so that KODI knows when the second episode really starts)

**Comment by PouuleT** [comment]
How will we know when the second episode really starts?

**Comment by gregdel** [comment]
There is a "runtime" on each file, if the first episode's duration is 45min then the bookmark of the second episode should be 2700 (the runtime is seconds). It might not be accurate every time but it should do the trick.

The real question is: "Is handling multiple episodes file worth the trouble ?"
